<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.qsdi</groupId>
    <artifactId>graph-operate</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>
    <modules>
        <module>graph-operate-insert-janusgraph</module>
        <module>graph-operate-query</module>
        <module>graph-operate-traversal-query</module>
        <module>graph-operate-common</module>
        <module>graph-operate-insert-gstore</module>
    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <relation-janusgraph.version>1.3.0-DEV</relation-janusgraph.version>
        <janusgraph.version>1.0.0-develop</janusgraph.version>
        <gstore.client.version>1.3.1-DEV</gstore.client.version>
        <guava.version>27.0-jre</guava.version>
        <lang3.version>3.7</lang3.version>
        <kafka.version>2.8.2</kafka.version>
        <hutool.version>5.3.6</hutool.version>


    </properties>

    <dependencyManagement>
        <dependencies>

        <dependency>
            <groupId>com.qsdi</groupId>
            <artifactId>ipbd-multi-graph-janusgraph-client</artifactId>
            <version>${relation-janusgraph.version}</version>
        </dependency>

            <dependency>
                <groupId>com.qsdi</groupId>
                <artifactId>ipbd-multi-graph-gstore-client</artifactId>
                <version>${gstore.client.version}</version>
            </dependency>

            <dependency>
                <groupId>com.qsdi</groupId>
                <artifactId>ipbd-multi-graph-gstore-impl</artifactId>
                <version>${gstore.client.version}</version>
            </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${guava.version}</version>
        </dependency>

            <!--        kafka client-->
            <dependency>
                <groupId>org.apache.kafka</groupId>
                <artifactId>kafka-clients</artifactId>
                <version>${kafka.version}</version>
            </dependency>

            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${lang3.version}</version>
            </dependency>
        </dependencies>

    </dependencyManagement>

    <dependencies>
<!--        <dependency>-->
<!--            <groupId>com.qsdi</groupId>-->
<!--            <artifactId>ipbd-multi-graph-janusgraph-client</artifactId>-->
<!--            <version>${relation-janusgraph.version}</version>-->
<!--        </dependency>-->




        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.25</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.24</version>
<!--            <scope>provided</scope>-->
        </dependency>

        <dependency>
            <groupId>io.dropwizard.metrics</groupId>
            <artifactId>metrics-core</artifactId>
            <version>4.2.15</version>
        </dependency>


        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>


</project>
