graph.name=performance_test
graph.gstore.connect.url=http://192.168.1.148:19111
graph.gstore.connect.timeout=20

#relation-center??????????stanford?????
data.source="relation-center"

#?????
vertex.enable=true
vertex.data.file=/opt/test/gstore/data/vertex_data1000W
vertex.insert.block.queue.size=100
#?????
edge.enable=false
edge.data.file_directory = /usr/graph_data_test/convert
edge.insert.block.queue.size=10000

queue.prepare.size=1
#queue.prepare.size=1000



#????????
batch.read-file-size=1000
#?????
batch.save-graph-size = 500
error.count=30
# ??????
consumer_parallelism=1

# ?????insert/update
insert.graph.type=insert

metric.csv.dir=/opt/test/gstore/graph-operate-insert-gstore
metric.period.second=10


kafka.enable-auto-commit=false
kafka.relation-topic=iras_gstore_mining2_entity_result
kafka.group-id=gstore_performance_test1
kafka.auto-offset-reset=earliest
kafka.bootstrap-servers=hadoop01:9092,hadoop02:9092,hadoop03:9092
kafka.max-poll-records=500
kafka.max-poll-interval=30000
kafka.session-timeout-ms=90000
kafka.max-partition-fetch-bytes=104857600
kafka.heartbeat-interval-ms=3000
kafka.fetch-min-bytes=1
